i seem to be missing a file
[martin@localhost source]$ mix ecto.setup
Compiling 13 files (.ex)
warning: render/1 was not implemented for QWeb.PageLive.

Make sure to either explicitly define a render/1 clause with a LiveView template:

    def render(assigns) do
      ~L"""
      ...
      """
    end

Or create a file at "/home/martin/stage/cl-elixir-generator/example/08_minimal_live/source/lib/q_web/live/page_live.html.leex" with the LiveView template.

  lib/q_web/live/page_live.ex:1: QWeb.PageLive (module)

== Compilation error in file lib/q_web/live/page_live.ex ==
** (CompileError) lib/q_web/live/page_live.ex:17: undefined function redirect/3
    (elixir 1.11.2) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.2) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7